name: Build Nix System

on: push

jobs:
  nixmake:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Run nixos-rebuild
        id: nixbuild
        continue-on-error: true
        run: nixos-rebuild build --flake github:rickyrnt/nixconfig#M04RYS8
      - name: Failure trace
        if: ${{ steps.nixbuild.outcome == 'failure' }}
        run: nixos-rebuild build --flake github:rickyrnt/nixconfig#M04RYS8 --show-trace